#!/usr/bin/env bash

BLACK=0xff24283b
WHITE=0xffa9b1d6
MAGENTA=0xffbb9af7
BLUE=0xff7aa2f7
CYAN=0xff7dcfff
GREEN=0xff9ece6a
YELLOW=0xffe0af68
ORANGE=0xffff9e64
RED=0xfff7768e
BAR_COLOR=0xff1a1b26
COMMENT=0xff565f89

TRANSPARENT=0x00000000

# General bar colors
ICON_COLOR=$WHITE  # Color of all icons
LABEL_COLOR=$WHITE # Color of all labels

ITEM_DIR="$HOME/.config/sketchybar/items"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

FONT="FiraCode Nerd Font"

PADDINGS=3

POPUP_BACKGROUND_COLOR=$BLACK
POPUP_BORDER_COLOR=$COMMENT

CORNER_RADIUS=15

SHADOW=on

# General bar and defaults

	# color="$BAR_COLOR" \
	# shadow="$SHADOW" \
	# blur_radius=20 \
sketchybar --bar \
	height=30 \
	color="$TRANSPARENT" \
	position=top \
	sticky=on \
	padding_right=0 \
	padding_left=3 \
	corner_radius="$CORNER_RADIUS" \
	y_offset=5 \
	margin=5 \
	notch_width=200 \
	--default updates=when_shown \
	icon.font="$FONT:Bold:13.5" \
	icon.color="$ICON_COLOR" \
	icon.padding_left="$PADDINGS" \
	icon.padding_right="$PADDINGS" \
	label.font="$FONT:Bold:13.0" \
	label.color="$LABEL_COLOR" \
	label.padding_left="$PADDINGS" \
	label.padding_right="$PADDINGS" \
	background.padding_right="$PADDINGS" \
	background.padding_left="$PADDINGS" \
	popup.background.border_width=1 \
	popup.background.corner_radius=11 \
	popup.background.border_color="$POPUP_BORDER_COLOR" \
	popup.background.color="$POPUP_BACKGROUND_COLOR" \
	popup.background.shadow.drawing="$SHADOW"

# Left
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Right
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"

#################### Finalizing Setup ####################

sketchybar --hotload true

sketchybar --update

echo "sketchybar configuration loaded.."
