require("vedant.plugins-setup")

-- plugin imports
require("vedant.plugins.comment")
require("vedant.plugins.nvim-tree")
require("vedant.plugins.nvim-cmp")
require("vedant.plugins.lualine")
require("vedant.plugins.todo-comments")
require("vedant.plugins.bufferline")
require("vedant.plugins.lsp.filetypes")
require("vedant.plugins.lsp.mason")
require("vedant.plugins.lsp.lspsaga")
require("vedant.plugins.lsp.lspconfig")
require("vedant.plugins.lsp.null-ls")
require("vedant.plugins.autopairs")
require("vedant.plugins.treesitter")
require("vedant.plugins.gitsigns")
require("vedant.plugins.telekasten")
require("vedant.plugins.copilot")
require("vedant.plugins.hlargs")
require("vedant.plugins.rust-tools")
require("vedant.plugins.ibl")
require("vedant.plugins.ufo")
require("vedant.plugins.leap")

-- core imports
require("vedant.core.remaps")
require("vedant.core.options")
