vim.g.mapleader = " "
vim.keymap.set("n", "<leader>e", ":Vex<cr>")
vim.keymap.set("n", "<leader>w", ":w<cr>")
vim.keymap.set("n", "<leader>q", ":q<cr>")
vim.keymap.set("n", "<leader>f", ":GFiles<CR>")
vim.keymap.set("n", "<leader>F", ":Files<CR>")
vim.keymap.set("n", "<leader>h", ":noh<CR>")
vim.keymap.set("n", "<leader>P", [["+P<CR>]])
vim.keymap.set("v", "<leader>p", [["_dP<CR>]])
vim.keymap.set("n", "<leader>y", [["+y]])
vim.keymap.set("v", "<leader>y", [["+y]])
vim.keymap.set("n", "<leader><CR>", ":so %<CR>")
vim.keymap.set("n", "<leader>va", "ggVG")
vim.keymap.set("i", "jk", "<esc>")
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
